### ISSUE TITLE
Can not fetch extensions correctly on Windows, such as `ms-vscode.js-debug`

### ISSUE THREAD

**Issue by erha19** [SmartIDE/eclipse-openvsx#4]
While fetching `ms-vscode.js-debug@1.67.2` extension on Windows, there have some errors like:

![image](https://user-images.githubusercontent.com/9823838/171131911-dd082625-376b-40bb-ba67-3290117768a7.png)

Only some extensions can be installed with OpenSumi download scripts.

![image](https://user-images.githubusercontent.com/9823838/171133067-3b375ff4-8400-4ef9-87f6-74d8ef92c825.png)

There may be some errors in the sync process with the Windows platform.

@zlweicoder can you fix this?

**Comment by erha19** [comment]
cc @ups216

**Comment by zlweicoder** [comment]
@erha19 
Already synced the required extension in [opensumi-ide-startup project download](https://github.com/opensumi/ide-startup/blob/master/scripts/extensions.json) (about 71 extensions 30000 versions).
I have tested and the download logic can executed successfully:
![image](https://user-images.githubusercontent.com/13825714/173258248-06d05e1e-8e2d-479c-9eff-4299712f17fe.png)

But there are three extensions you need to fix:
1. node-debug : change the namespace to 'ms-vscode' and use the suitable version.
2. node-debug2 : change the namespace to 'ms-vscode' and use the suitable version.
3. markdown-basics: cannot find this extension in either openvsx marketplace and vscode marketplace, so smartide marketplace cannot sync this one.

Please try to execute the download logic and be free to let us know if there are further questions.

**Comment by zlweicoder** [comment]
@erha19 
Please check if there are further questions about this issue, I will close it if everything goes well.

**Comment by zlweicoder** [comment]
@erha19 
An elastic search engine has added to marketplace.smartide.cn with search speed and stability improved a lot.
